###
GET http://localhost:3003/api/blogs HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWQiOiI2N2ViZTFiM2QxMjZkYWNlOTQ5OWMxYjQiLCJpYXQiOjE3NDM1Mjk1NjEsImV4cCI6MTc0MzUzMzE2MX0.9G5J61iy7dunN_N8A2FJS4TuEeU8foe55c3KS0st_x8