POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3ZWJjZTdkOTkzM2UyYWY0MjYwNzNmNiIsImlhdCI6MTc0MzUwODIyM30.eN2xlxGac1eAmrzCHomLOfWxl2jrs5XR29bFDA7sUu4

{
    "content": "Single page apps use token based auth",
    "important": true
}
